# >> post topic 

# POST http://localhost:3001/topics HTTP/1.1
# content-type: application/json

# {
#     "topic": "react i vue",
#     "votes": 0,
#     "addedDate": 457754,
#     "userAdded": "miki"
# }
# POST http://localhost:3001/meetings HTTP/1.1
# content-type: application/json

# {
#     "date": 1254152,
#     "topic": "jakis temat",
#     "leader": "Andrzej",
#     "duration": "1h30m",
#     "resourcesURL": "brak",
#     "usefulLinks": ["gogle","allegro"],
#     "description": "brak opisu"
# }
# get topics

GET http://localhost:3001/meetings


# >> get paginated topics

# GET http://localhost:3001/topics?page=2&limit=3


# >> get all topics
# GET http://localhost:3001/meetings/all

# >> get paginated topics
# GET http://localhost:3001/meetings?page=2&limit=2

GET http://localhost:3001/topics?page=1&limit=5